name: Basic Static Check

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Vérifier la présence des fichiers clés
        run: |
          test -f index.html
          echo "index.html trouvé, OK."
